// Runtime operands; no constant tensors. Generated by tools/generate_inputs.py.
module {
  func.func @matmul(%x: tensor<1x32xf32>, %w: tensor<32x16xf32>) -> tensor<1x16xf32> {
    %c0 = arith.constant 0 : index
    %zero = arith.constant 0.0 : f32
    %empty = tensor.empty() : tensor<1x16xf32>
    %init = linalg.fill ins(%zero : f32) outs(%empty : tensor<1x16xf32>) -> tensor<1x16xf32>
    %mm = linalg.matmul ins(%x, %w : tensor<1x32xf32>, tensor<32x16xf32>) outs(%init : tensor<1x16xf32>) -> tensor<1x16xf32>
    return %mm : tensor<1x16xf32>
  }

  func.func @bias_relu(%a: tensor<1x16xf32>, %bias: tensor<16xf32>) -> tensor<1x16xf32> {
    %c0 = arith.constant 0 : index
    %zero = arith.constant 0.0 : f32
    %empty = tensor.empty() : tensor<1x16xf32>
    %act = linalg.generic {
      indexing_maps = [affine_map<(m,n)->(m,n)>, affine_map<(m,n)->(n)>, affine_map<(m,n)->(m,n)>],
      iterator_types = ["parallel", "parallel"]
    } ins(%a, %bias : tensor<1x16xf32>, tensor<16xf32>) outs(%empty : tensor<1x16xf32>) {
    ^bb0(%v: f32, %bias_v: f32, %unused: f32):
      %sum = arith.addf %v, %bias_v : f32
      %relu = arith.maximumf %sum, %zero : f32
      linalg.yield %relu : f32
    } -> tensor<1x16xf32>
    return %act : tensor<1x16xf32>
  }

  func.func @row_sum(%a: tensor<1x16xf32>) -> tensor<1xf32> {
    %c0 = arith.constant 0 : index
    %zero = arith.constant 0.0 : f32
    %row_empty = tensor.empty() : tensor<1xf32>
    %acc = linalg.fill ins(%zero : f32) outs(%row_empty : tensor<1xf32>) -> tensor<1xf32>
    %reduced = linalg.generic {
      indexing_maps = [affine_map<(m,n)->(m,n)>, affine_map<(m,n)->(m)>],
      iterator_types = ["parallel", "reduction"]
    } ins(%a : tensor<1x16xf32>) outs(%acc : tensor<1xf32>) {
    ^bb0(%v: f32, %acc_v: f32):
      %sum = arith.addf %v, %acc_v : f32
      linalg.yield %sum : f32
    } -> tensor<1xf32>
    return %reduced : tensor<1xf32>
  }

  func.func @fragment(%x: tensor<1x32xf32>, %w: tensor<32x16xf32>, %bias: tensor<16xf32>) -> tensor<1xf32> {
    %c0 = arith.constant 0 : index
    %zero = arith.constant 0.0 : f32
    %empty = tensor.empty() : tensor<1x16xf32>
    %init = linalg.fill ins(%zero : f32) outs(%empty : tensor<1x16xf32>) -> tensor<1x16xf32>
    %mm = linalg.matmul ins(%x, %w : tensor<1x32xf32>, tensor<32x16xf32>) outs(%init : tensor<1x16xf32>) -> tensor<1x16xf32>
    %act = linalg.generic {
      indexing_maps = [affine_map<(m,n)->(m,n)>, affine_map<(m,n)->(n)>, affine_map<(m,n)->(m,n)>],
      iterator_types = ["parallel", "parallel"]
    } ins(%mm, %bias : tensor<1x16xf32>, tensor<16xf32>) outs(%empty : tensor<1x16xf32>) {
    ^bb0(%v: f32, %bias_v: f32, %unused: f32):
      %sum = arith.addf %v, %bias_v : f32
      %relu = arith.maximumf %sum, %zero : f32
      linalg.yield %relu : f32
    } -> tensor<1x16xf32>
    %row_empty = tensor.empty() : tensor<1xf32>
    %acc = linalg.fill ins(%zero : f32) outs(%row_empty : tensor<1xf32>) -> tensor<1xf32>
    %reduced = linalg.generic {
      indexing_maps = [affine_map<(m,n)->(m,n)>, affine_map<(m,n)->(m)>],
      iterator_types = ["parallel", "reduction"]
    } ins(%act : tensor<1x16xf32>) outs(%acc : tensor<1xf32>) {
    ^bb0(%v: f32, %acc_v: f32):
      %sum = arith.addf %v, %acc_v : f32
      linalg.yield %sum : f32
    } -> tensor<1xf32>
    return %reduced : tensor<1xf32>
  }
}
