#!/usr/bin/env python3
"""Generate standard Linalg IR; generated inputs are checked into the repository."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]


def module(m, k, n):
    x, w, a, b, out = (f"tensor<{m}x{k}xf32>", f"tensor<{k}x{n}xf32>",
                        f"tensor<{m}x{n}xf32>", f"tensor<{n}xf32>", f"tensor<{m}xf32>")
    dim = "%m" if m == "?" else ""
    prefix = "%c0 = arith.constant 0 : index\n    %zero = arith.constant 0.0 : f32\n"
    def alloc(arg, ty, result_ty, name):
        size = f"    %m = tensor.dim {arg}, %c0 : {ty}\n" if m == "?" else ""
        return size + f"    %{name} = tensor.empty({dim}) : {result_ty}\n"
    mm = (f"    %init = linalg.fill ins(%zero : f32) outs(%empty : {a}) -> {a}\n"
          f"    %mm = linalg.matmul ins(%x, %w : {x}, {w}) outs(%init : {a}) -> {a}\n")
    def act(arg):
        return f'''    %act = linalg.generic {{
      indexing_maps = [affine_map<(m,n)->(m,n)>, affine_map<(m,n)->(n)>, affine_map<(m,n)->(m,n)>],
      iterator_types = ["parallel", "parallel"]
    }} ins({arg}, %bias : {a}, {b}) outs(%empty : {a}) {{
    ^bb0(%v: f32, %bias_v: f32, %unused: f32):
      %sum = arith.addf %v, %bias_v : f32
      %relu = arith.maximumf %sum, %zero : f32
      linalg.yield %relu : f32
    }} -> {a}
'''
    def reduce(arg):
        return f'''    %row_empty = tensor.empty({dim}) : {out}
    %acc = linalg.fill ins(%zero : f32) outs(%row_empty : {out}) -> {out}
    %reduced = linalg.generic {{
      indexing_maps = [affine_map<(m,n)->(m,n)>, affine_map<(m,n)->(m)>],
      iterator_types = ["parallel", "reduction"]
    }} ins({arg} : {a}) outs(%acc : {out}) {{
    ^bb0(%v: f32, %acc_v: f32):
      %sum = arith.addf %v, %acc_v : f32
      linalg.yield %sum : f32
    }} -> {out}
'''
    funcs = [
        f"  func.func @matmul(%x: {x}, %w: {w}) -> {a} {{\n    " + prefix + alloc("%x", x, a, "empty") + mm + f"    return %mm : {a}\n  }}\n",
        f"  func.func @bias_relu(%a: {a}, %bias: {b}) -> {a} {{\n    " + prefix + alloc("%a", a, a, "empty") + act("%a") + f"    return %act : {a}\n  }}\n",
        f"  func.func @row_sum(%a: {a}) -> {out} {{\n    " + prefix + (f"    %m = tensor.dim %a, %c0 : {a}\n" if m == "?" else "") + reduce("%a") + f"    return %reduced : {out}\n  }}\n",
        f"  func.func @fragment(%x: {x}, %w: {w}, %bias: {b}) -> {out} {{\n    " + prefix + alloc("%x", x, a, "empty") + mm + act("%mm") + reduce("%act") + f"    return %reduced : {out}\n  }}\n",
    ]
    return "// Runtime operands; no constant tensors. Generated by tools/generate_inputs.py.\nmodule {\n" + "\n".join(funcs) + "}\n"


def main():
    shapes = [("tiny", 1, 32, 16), ("tail", 7, 33, 17), ("aligned", 64, 64, 32),
              ("dynamic", "?", 32, 16)]
    manifests = []
    for name, m, k, n in shapes:
        (ROOT / "inputs" / f"{name}.mlir").write_text(module(m, k, n))
        manifests.append({"id": name, "m": m, "k": k, "n": n,
                          "batches": [1, 7, 64] if m == "?" else [m],
                          "input": f"inputs/{name}.mlir"})
    (ROOT / "manifest.json").write_text(json.dumps({
        "schema_version": 1, "seed": 20260906, "dtype": "float32",
        "driver": "local-sync", "runtime_threads": 1,
        "rtol": 2e-5, "atol": 2e-5,
        "finite_reference": "float64 accumulation; float32 runtime inputs",
        "special_values": "NaN/positive infinity/negative infinity masks must match; signed zeros compare numerically",
        "layout": "C-contiguous required; strided inputs rejected by contract",
        "shapes": manifests,
        "configurations": {"untiled": ["--iree-opt-data-tiling=false"],
                           "tiled": ["--iree-opt-data-tiling=true"]},
    }, indent=2) + "\n")


if __name__ == "__main__":
    main()
